### ISSUE TITLE
in summariseClinicalRecords in ageGroup names are needed in the list

### ISSUE THREAD

**Issue by cecicampanile** [OHDSI/OmopSketch#181]
When stratifying by age groups in summariseClinicalRecords, names in the list defined as ageGroup are required or this error occurs:

>  Error in `purrr::map()`:
> ℹ In index: 1.
> Caused by error in `dplyr::select()`:
> ! Can't select columns that don't exist.
> ✖ Column `age_group` doesn't exist.

**Comment by martaalcalde** [comment]
Should be fixed in the developer version!
