### ISSUE TITLE
Allow interval = NULL, unitInterval = NULL in summariseConceptCounts when no stratification per unit interval of time wants to be performed

### ISSUE THREAD

**Issue by martaalcalde** [OHDSI/OmopSketch#195]
What do you think, @catalamarti ?

**Comment by catalamarti** [comment]
Mmmm The more I think would be nice to align with IncidencePrevalence:
https://darwin-eu.github.io/IncidencePrevalence/reference/estimateIncidence.html

Then my suggestion would be two arguments:
- interval (overall/years/quarters/months/weeks/days) we can for the moment only allow
- intervalValue: by default 1, but can allow to change it

What do you think @martaalcalde
This would allow overall option (happy to include an option that if NULL -> overall)
Allow the value thingy
Align with IncidencePrevalence

**Comment by martaalcalde** [comment]
Change it in:
- summariseRecordCount
- summariseConceptCount
- summariseInObservation
