### ISSUE TITLE
Include sampling options

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/OmopSketch#210]
Users could sample their whole cdm before running functions in OmopSketch, but it could be nice that there is also a sampling option within OmopSketch functions where a sample would be taken of the records in a table in question (e.g. drug exposure). This could then be used instead of sampling people from the person table (as that then requires a join between the sampled person table and the drug exposure table).

I would even be tempted to have this as a default, say of a million records .....

For example implementation see https://github.com/OHDSI/CohortConstructor/blob/9cca6d392e0091d9c2d7a2e468c3d95749e30afd/R/sampleCohorts.R#L40

**Comment by catalamarti** [comment]
Add argument `sample` in:
- summariseRecordCount
- summariseClinicalRecords
- summariseConceptIdCount
- summariseConceptSetcount
