### ISSUE TITLE
Query benchmarks - in scope for OmopSketch?

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/OmopSketch#213]
Whether incorporating something like this is in scope https://github.com/oxford-pharmacoepi/ServerBenchmark?

**Comment by catalamarti** [comment]
I dont think it is of the scope of OmopSketch, but we could implement it as part of the characterisation @cecicampanile and later see where it fits.
Unless @martaalcalde thinks that it fits well in OmopSketch

**Comment by martaalcalde** [comment]
Happy if Cecilia implements this in the characterisation!
