### ISSUE TITLE
include all columns in mocks

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/OmopSketch#215]
Checks should pass installing `pak::pkg_install("darwin-eu-dev/omopgenerics@issue_519")`

https://github.com/darwin-eu-dev/omopgenerics/issues/519

**Comment by cecicampanile** [comment]
need more info + having issues installing this branch of omopgenerics

**Comment by cecicampanile** [comment]
only column missing is invalid_reason  in drug_strength
