### ISSUE TITLE
rename functions

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/OmopSketch#262]
- `summariseConceptCounts` -> summariseConceptSetCount`
- Add deprecation warning to `summariseConceptCounts`

**Comment by cecicampanile** [comment]
lifecycle::deprecate_warn(when = "0.2.0", what = "summariseAllConcetpt()", with = "summariseConceptIdCount()")

**Comment by cecicampanile** [comment]
conceptId -> conceptSet
