### ISSUE TITLE
summariseCodeUse()

### ISSUE THREAD

**Issue by martaalcalde** [OHDSI/OmopSketch#70]
- allow for different levels
- all concepts at the same time
- strata levels mixed between them

**Comment by catalamarti** [comment]
- to consider if we want to functions (codelist vs concept_id level)
- person count vs record count
-

**Comment by catalamarti** [comment]
summariseCodeUse <- function(x,
                             cdm,
                             countBy = c("record", "person"),
                             byConcept = TRUE,
                             byYear = FALSE,
                             bySex = FALSE,
                             ageGroup = NULL){

This is the current function in CodelistGenerator, is there anything extra that we would need @martaalcalde ?

**Comment by martaalcalde** [comment]
Hi Marti, see my proposal in issue #37
