### ISSUE TITLE
create an internal functions

### ISSUE THREAD

**Issue by martaalcalde** [OHDSI/OmopSketch#71]
create an internal function for the following three functions: summariseRecordCount(), summariseClinicalRecords() and summariseCodeUse()

**Comment by martaalcalde** [comment]
@catalamarti do you remember what was this about?

**Comment by catalamarti** [comment]
summariseResultCount, summariseClinicalRecord and summariseCodeUse could share a unique internal function that would do the work. This would make the package lightweight and more robust.
Externally the functions would continue working the same.

**Comment by catalamarti** [comment]
- summariseRecordCount
- summariseConceptIdCount
- summariseConceptSetCount
- summariseClinicalRecord
- summariseMissingData

should share a common internal function
